import { RankingInfo, compareItems } from "@tanstack/match-sorter-utils";
import { Row, sortingFns } from "@tanstack/react-table";

export function fuzzySort<T>(rowA: Row<T>, rowB: Row<T>, columnId: string) {
  let dir = 0;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rowARank: RankingInfo = (rowA.columnFiltersMeta[columnId] as any)
    ?.itemRank;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rowBRank: RankingInfo = (rowB.columnFiltersMeta[columnId] as any)
    ?.itemRank;

  // Only sort by rank if the column has ranking information
  if (!!rowARank && !!rowBRank) {
    dir = compareItems(rowARank, rowBRank);
  }

  // Provide an alphanumeric fallback for when the item ranks are equal
  return dir === 0 ? sortingFns.alphanumeric(rowA, rowB, columnId) : dir;
}

export interface LegTopic {
  value: string;
  label: string;
}

export const topics: Array<LegTopic> = [
  { value: "", label: "All" },
  { value: "15726", label: "911" },
  { value: "16007", label: "988" },
  { value: "15655", label: "Abortion" },
  { value: "16054", label: "Accountancy, board" },
  { value: "16052", label: "Accountants and accounting" },
  { value: "15496", label: "Actions and proceedings" },
  { value: "16013", label: "Address confidentiality program" },
  { value: "15610", label: "Administrative office of the courts" },
  { value: "15557", label: "Administrative procedure" },
  {
    value: "16097",
    label: "Adult entertainment establishments and entertainers",
  },
  { value: "16095", label: "Adult family homes" },
  { value: "15821", label: "Advertising" },
  { value: "15667", label: "Aeronautics" },
  { value: "15669", label: "Aerospace" },
  { value: "15566", label: "Affordable housing" },
  { value: "15865", label: "African americans" },
  { value: "15595", label: "Agriculture" },
  { value: "15594", label: "Agriculture, department" },
  { value: "15950", label: "Air pollution control authorities" },
  { value: "15658", label: "Air quality and pollution" },
  { value: "15889", label: "Airplanes and aircraft" },
  { value: "15888", label: "Airports" },
  { value: "15488", label: "Alcoholic beverages" },
  { value: "16018", label: "Ambulances" },
  {
    value: "15985",
    label: "Andy hill cancer research endowment (care) fund",
  },
  { value: "15653", label: "Animals" },
  { value: "15688", label: "Apartment owner associations" },
  { value: "15790", label: "Appeals, court of" },
  { value: "16140", label: "Appliances" },
  { value: "15997", label: "Applied behavior analysis" },
  { value: "15545", label: "Apprentices and apprenticeship programs" },
  {
    value: "16108",
    label: "Apprenticeship and training council, washington state",
  },
  { value: "15804", label: "Aquatic lands" },
  {
    value: "16131",
    label: "Archaeology and historic preservation, department",
  },
  { value: "16039", label: "Architects" },
  { value: "15679", label: "Arenas" },
  { value: "15955", label: "Art and artworks" },
  { value: "16066", label: "Artificial intelligence (ai)" },
  { value: "15958", label: "Arts commission" },
  { value: "15915", label: "Asian americans" },
  {
    value: "15992",
    label: "Asian pacific american affairs, state commission",
  },
  { value: "15988", label: "Asian pacific americans" },
  { value: "16139", label: "Assault" },
  { value: "15620", label: "Attorney general" },
  { value: "15624", label: "Attorneys" },
  { value: "15784", label: "Auditor, state" },
  { value: "15604", label: "Auditors and auditing" },
  { value: "15999", label: "Autism" },
  { value: "16078", label: "Autonomous vehicles" },
  { value: "15668", label: "Aviation" },
  { value: "15823", label: "Background checks" },
  { value: "15716", label: "Bail and bail bonds" },
  { value: "16040", label: "Banks and banking" },
  { value: "15586", label: "Barbers" },
  { value: "15788", label: "Batteries" },
  { value: "15506", label: "Behavioral health" },
  { value: "15789", label: "Beverages and beverage containers" },
  { value: "15868", label: "Bicycles" },
  { value: "16128", label: "Birds" },
  { value: "15676", label: "Blind" },
  { value: "16087", label: "Blind, department of services for the" },
  { value: "15993", label: "Blind, state school for the" },
  { value: "16085", label: "Boards and commissions" },
  { value: "15776", label: "Boats and boating" },
  { value: "15750", label: "Bonds" },
  { value: "15851", label: "Boundaries" },
  { value: "16134", label: "Boundary review boards" },
  { value: "15455", label: "Bridges" },
  { value: "16082", label: "British columbia" },
  { value: "16071", label: "Broadband" },
  {
    value: "15986",
    label: "Broadband office, governor&#x27;s statewide",
  },
  { value: "16117", label: "Budget stabilization account" },
  { value: "15708", label: "Budgets" },
  { value: "15614", label: "Building code council" },
  { value: "15615", label: "Building codes and permits" },
  { value: "15684", label: "Buildings, commercial" },
  { value: "15683", label: "Buildings, state" },
  { value: "15553", label: "Business and occupation tax" },
  { value: "15493", label: "Business corporations" },
  { value: "15494", label: "Business organizations" },
  { value: "15466", label: "Businesses" },
  { value: "16145", label: "Cameras" },
  { value: "15818", label: "Campaign disclosure and contribution" },
  { value: "15760", label: "Cancer" },
  { value: "15709", label: "Cannabis" },
  { value: "16121", label: "Capital gains tax" },
  { value: "15824", label: "Capitol campus, state" },
  { value: "15951", label: "Career and technical education" },
  { value: "15714", label: "Caseload forecast council" },
  { value: "16034", label: "Catalytic converters" },
  { value: "15920", label: "Cats" },
  { value: "15665", label: "Cemeteries and cemetery districts" },
  { value: "15841", label: "Central washington university" },
  { value: "16053", label: "Certified public accountants" },
  { value: "15780", label: "Charitable organizations" },
  { value: "15984", label: "Charter school commission" },
  { value: "15706", label: "Charter schools" },
  { value: "16051", label: "Check cashers and sellers" },
  {
    value: "15874",
    label: "Chief information officer, office of the state",
  },
  { value: "15829", label: "Child care" },
  { value: "16075", label: "Child custody" },
  { value: "15964", label: "Child protective services" },
  { value: "15837", label: "Child support" },
  { value: "15769", label: "Child welfare services" },
  { value: "15509", label: "Children" },
  {
    value: "15627",
    label: "Children, youth, and families, department",
  },
  { value: "15795", label: "Circuses and carnivals" },
  { value: "15457", label: "Cities and towns" },
  {
    value: "15970",
    label: "Citizens&#x27; commission on salaries for elected officials",
  },
  { value: "16046", label: "Citizenship" },
  { value: "15497", label: "Civil actions and procedure" },
  { value: "16003", label: "Civil legal aid, office" },
  { value: "16022", label: "Civil protection orders" },
  { value: "15870", label: "Civil service" },
  { value: "15800", label: "Clemency and pardons board" },
  { value: "15657", label: "Clergy" },
  { value: "15746", label: "Climate" },
  { value: "15961", label: "Collection agencies and debt collection" },
  { value: "15742", label: "Collective bargaining" },
  { value: "15441", label: "Colleges and universities" },
  { value: "15991", label: "Columbia river" },
  { value: "15529", label: "Commerce, department" },
  { value: "15695", label: "Commercial buildings" },
  { value: "15752", label: "Commercial vessels and shipping" },
  { value: "15641", label: "Commissioner of public lands" },
  { value: "16086", label: "Commissions and boards" },
  { value: "15779", label: "Commodity boards and commissions" },
  { value: "15685", label: "Common interest communities" },
  { value: "15442", label: "Community and technical colleges" },
  {
    value: "15946",
    label: "Community and technical colleges, state board for",
  },
  { value: "15833", label: "Community economic revitalization board" },
  {
    value: "15936",
    label: "Community preservation and development authorities",
  },
  { value: "15648", label: "Compost and composting" },
  { value: "15697", label: "Computers" },
  { value: "15475", label: "Concurrent resolutions" },
  { value: "15686", label: "Condominiums" },
  { value: "15727", label: "Conservation" },
  { value: "15814", label: "Conservation commission" },
  { value: "16010", label: "Conservation districts" },
  { value: "16058", label: "Conservatorship" },
  { value: "15864", label: "Consolidated technology services agency" },
  { value: "15516", label: "Constitution, state" },
  { value: "15853", label: "Constitution, u.s." },
  { value: "15766", label: "Construction" },
  { value: "15698", label: "Consumer protection" },
  {
    value: "16074",
    label: "Consumer reporting and consumer reporting agencies",
  },
  { value: "15712", label: "Contraception" },
  { value: "15703", label: "Contractors" },
  { value: "15924", label: "Contracts" },
  { value: "15798", label: "Cooperative associations" },
  { value: "16096", label: "Coroners and medical examiners" },
  { value: "15495", label: "Corporations" },
  { value: "15617", label: "Correctional facilities and jails" },
  { value: "15954", label: "Corrections officers" },
  { value: "16107", label: "Corrections ombuds, office" },
  { value: "15580", label: "Corrections, department" },
  { value: "15745", label: "Cosmetics" },
  {
    value: "15585",
    label:
      "Cosmetologists, hair designers, barbers, manicurists, and estheticians",
  },
  { value: "15607", label: "Counselors and counseling" },
  { value: "15458", label: "Counties" },
  { value: "15974", label: "County auditors" },
  { value: "15480", label: "Courts" },
  { value: "15558", label: "Covid-19" },
  { value: "15774", label: "Covid-19 and coronavirus" },
  { value: "15962", label: "Credit and debit cards" },
  { value: "16073", label: "Credit history and credit reporting" },
  { value: "15878", label: "Credit services organizations" },
  { value: "15773", label: "Crime victims advocacy, office" },
  { value: "15626", label: "Crime victims&#x27; compensation program" },
  { value: "15443", label: "Crimes" },
  { value: "15621", label: "Criminal justice training commission" },
  { value: "15512", label: "Criminal offenders" },
  { value: "15513", label: "Criminal procedure" },
  { value: "16153", label: "Crops" },
  { value: "15733", label: "Cryptocurrency" },
  { value: "15732", label: "Currency" },
  { value: "15931", label: "Dairy farms and dairy products" },
  { value: "15675", label: "Deaf" },
  {
    value: "16008",
    label: "Deaf and hard of hearing youth, washington center for",
  },
  { value: "16123", label: "Deaf and hard of hearing, office of the" },
  { value: "15654", label: "Death" },
  { value: "15927", label: "Dental hygienists" },
  { value: "16093", label: "Dental quality assurance commission" },
  { value: "15967", label: "Dental therapists" },
  { value: "15767", label: "Dentists and dentistry" },
  {
    value: "15609",
    label: "Developmental disabilities, individuals with",
  },
  { value: "15600", label: "Dinosaurs" },
  { value: "15611", label: "Disabilities, persons with" },
  { value: "15786", label: "Discrimination" },
  { value: "15791", label: "District courts" },
  { value: "15905", label: "Document recording" },
  { value: "15919", label: "Dogs" },
  { value: "15510", label: "Domestic relations" },
  { value: "15605", label: "Domestic violence" },
  { value: "16138", label: "Driver training schools" },
  { value: "15491", label: "Drivers and drivers&#x27; licenses" },
  { value: "15490", label: "Driving under the influence" },
  { value: "16072", label: "Drug courts" },
  { value: "15470", label: "Drugs" },
  {
    value: "15937",
    label: "Early childhood education and assistance program",
  },
  { value: "15938", label: "Early learning" },
  { value: "15498", label: "Easements" },
  { value: "15842", label: "Eastern washington university" },
  { value: "15649", label: "Ecology, department" },
  { value: "16015", label: "Economic and revenue forecast council" },
  { value: "15831", label: "Economic development" },
  { value: "15916", label: "Education data center" },
  { value: "16024", label: "Education ombuds, office" },
  { value: "15877", label: "Education, state board of" },
  { value: "15546", label: "Educational service districts" },
  { value: "16019", label: "Elected and appointed officials" },
  { value: "15634", label: "Elections" },
  {
    value: "15872",
    label: "Electricians and electrical installations",
  },
  { value: "16149", label: "Electricity" },
  { value: "15876", label: "Electronic products" },
  { value: "16012", label: "Emergencies" },
  { value: "15542", label: "Emergency management and services" },
  { value: "15785", label: "Emergency medical services" },
  { value: "15559", label: "Emergency, state of" },
  { value: "15531", label: "Employment and employees" },
  { value: "15528", label: "Employment security department" },
  { value: "15592", label: "Energy" },
  { value: "15796", label: "Energy facility site evaluation council" },
  { value: "15909", label: "Enterprise services, department" },
  { value: "15866", label: "Environment" },
  {
    value: "16100",
    label: "Environmental and land use hearings office",
  },
  { value: "15647", label: "Environmental health and safety" },
  { value: "16104", label: "Environmental justice" },
  { value: "16105", label: "Environmental justice council" },
  { value: "15947", label: "Equity, washington state office of" },
  { value: "16122", label: "Erotic material" },
  { value: "15757", label: "Estate tax" },
  { value: "15499", label: "Estates" },
  { value: "15500", label: "Estates, trusts, and probate" },
  { value: "15589", label: "Estheticians" },
  { value: "15782", label: "Ethics in government" },
  { value: "15844", label: "Evergreen state college, the" },
  { value: "15808", label: "Eviction" },
  { value: "15718", label: "Evidence" },
  { value: "15672", label: "Examining board of psychology" },
  { value: "15556", label: "Excise taxes" },
  { value: "15912", label: "Explosives" },
  { value: "16001", label: "Exports" },
  { value: "16143", label: "Fairs" },
  { value: "15755", label: "Family and medical leave, paid" },
  { value: "15596", label: "Farms and farming" },
  { value: "16103", label: "Fashion industry" },
  { value: "15940", label: "Fentanyl" },
  { value: "15751", label: "Ferries" },
  { value: "15989", label: "Filipino americans" },
  { value: "15925", label: "Financial institutions" },
  { value: "15907", label: "Financial institutions, department" },
  { value: "15725", label: "Financial management, office" },
  { value: "15583", label: "Fire protection" },
  { value: "15582", label: "Fire protection districts" },
  { value: "15503", label: "Firearms" },
  { value: "15473", label: "Firefighters" },
  { value: "15953", label: "First responders" },
  { value: "15835", label: "Fiscal notes" },
  { value: "15741", label: "Fish" },
  { value: "15968", label: "Fish and wildlife commission" },
  { value: "15464", label: "Fish and wildlife, department" },
  { value: "15535", label: "Fishing" },
  { value: "16069", label: "Fitness centers" },
  { value: "15793", label: "Floods and flood control" },
  { value: "16035", label: "Floor resolutions" },
  { value: "15536", label: "Food and food products" },
  { value: "15933", label: "Food assistance" },
  { value: "15932", label: "Food banks" },
  { value: "16016", label: "Foreign governments" },
  { value: "15591", label: "Forest practices and products" },
  { value: "16005", label: "Forestlands" },
  { value: "15599", label: "Fossils" },
  { value: "15704", label: "Foster care" },
  { value: "15590", label: "Fuels" },
  { value: "16041", label: "Funerals and burial" },
  { value: "15650", label: "Fur farming and fur products" },
  { value: "15923", label: "Gambling" },
  { value: "15948", label: "Gambling commission" },
  { value: "15806", label: "Gas stations" },
  { value: "16144", label: "Gender" },
  { value: "16020", label: "Gender and justice commission" },
  { value: "16077", label: "Gender expression" },
  { value: "15603", label: "Gender identity" },
  { value: "16111", label: "Geology and geologists" },
  { value: "15982", label: "Gift certificates and cards" },
  { value: "15476", label: "Governor" },
  {
    value: "16135",
    label:
      "Governor&#x27;s interagency coordinating council on health disparities",
  },
  { value: "15569", label: "Growth management" },
  { value: "15894", label: "Growth management hearings board" },
  { value: "15768", label: "Guardianship" },
  { value: "15517", label: "Gubernatorial appointments" },
  {
    value: "16084",
    label: "Gubernatorial appointments to offices or positions",
  },
  { value: "15587", label: "Hair designers" },
  { value: "15444", label: "Harassment" },
  { value: "15689", label: "Hazardous materials" },
  { value: "15858", label: "Hazardous substances tax" },
  { value: "15787", label: "Hazardous waste" },
  { value: "15451", label: "Health and safety, public" },
  { value: "15772", label: "Health benefit exchange" },
  { value: "15560", label: "Health care" },
  { value: "15518", label: "Health care authority" },
  { value: "15707", label: "Health care benefit managers" },
  { value: "15636", label: "Health care facilities" },
  { value: "16088", label: "Health care facilities authority" },
  { value: "15439", label: "Health care professions and providers" },
  { value: "15840", label: "Health care workers" },
  { value: "15996", label: "Health corps, washington" },
  { value: "15929", label: "Health departments, local" },
  { value: "15527", label: "Health, department" },
  { value: "15533", label: "Health, state board of" },
  { value: "15737", label: "High hazard facilities" },
  { value: "16089", label: "Higher education facilities authority" },
  { value: "15956", label: "Historical societies" },
  { value: "15483", label: "Holidays and observances" },
  { value: "15575", label: "Home-based instruction" },
  { value: "15564", label: "Homeless persons" },
  { value: "15687", label: "Homeowners&#x27; associations" },
  { value: "15565", label: "Homes and housing" },
  { value: "15943", label: "Horse racing" },
  { value: "15944", label: "Horse racing commission" },
  { value: "15942", label: "Horses" },
  { value: "15749", label: "Hospitality industry" },
  { value: "15635", label: "Hospitals" },
  { value: "16031", label: "Hotels" },
  { value: "15736", label: "Hours" },
  { value: "15479", label: "House resolutions" },
  { value: "15567", label: "Housing and homes" },
  { value: "16047", label: "Housing authorities" },
  { value: "15815", label: "Housing finance commission" },
  { value: "16113", label: "Hulk haulers and scrap processors" },
  { value: "15664", label: "Human remains" },
  { value: "15801", label: "Human rights commission" },
  { value: "15913", label: "Hunting" },
  { value: "15645", label: "Identicards" },
  { value: "15633", label: "Identification" },
  {
    value: "15602",
    label: "Immigration, immigrants, and immigration status",
  },
  { value: "15630", label: "Immunization" },
  { value: "15856", label: "Impact fees" },
  { value: "15694", label: "Incarcerated individuals" },
  { value: "16142", label: "Income tax" },
  { value: "16062", label: "Independent investigations, office" },
  { value: "15884", label: "Indeterminate sentence review board" },
  { value: "15544", label: "Indians" },
  { value: "15662", label: "Indigent persons" },
  { value: "15729", label: "Industrial insurance" },
  { value: "15753", label: "Initiative and referendum" },
  { value: "16141", label: "Initiatives" },
  {
    value: "15892",
    label: "Institutional review board, washington state",
  },
  { value: "15539", label: "Insurance" },
  { value: "15581", label: "Insurance commissioner" },
  {
    value: "15759",
    label: "Intellectual disabilities, individuals with",
  },
  { value: "16081", label: "International relations" },
  {
    value: "16080",
    label: "International relations and protocol, office",
  },
  { value: "15696", label: "Internet" },
  { value: "15677", label: "Interpreters" },
  { value: "15744", label: "Investment board, state" },
  { value: "15886", label: "Irrigation districts" },
  { value: "15713", label: "Joint memorials" },
  { value: "15515", label: "Joint resolutions" },
  { value: "15481", label: "Judges" },
  { value: "15692", label: "Judgments" },
  { value: "15770", label: "Jurors and juries" },
  { value: "16011", label: "Juvenile court and juvenile offenders" },
  { value: "15570", label: "Juveniles and juvenile court" },
  { value: "15530", label: "Labor" },
  { value: "15625", label: "Labor and industries, department" },
  { value: "15904", label: "Lakes and reservoirs" },
  { value: "15832", label: "Land use planning and development" },
  { value: "15693", label: "Landlord and tenant" },
  {
    value: "15472",
    label: "Law enforcement and law enforcement personnel",
  },
  { value: "15949", label: "Lead" },
  { value: "15922", label: "Legal financial obligations" },
  { value: "15880", label: "Legal notices" },
  {
    value: "15965",
    label: "Legislative audit and review committee, joint (jlarc)",
  },
  {
    value: "16021",
    label: "Legislative evaluation and accountability program (leap) committee",
  },
  { value: "15477", label: "Legislature" },
  { value: "16152", label: "Lgbtq people" },
  { value: "15761", label: "Libraries" },
  { value: "16068", label: "License plates" },
  { value: "15899", label: "Licenses and licensing" },
  { value: "15526", label: "Licensing, department" },
  { value: "15839", label: "Liens" },
  { value: "16094", label: "Lieutenant governor" },
  { value: "16017", label: "Lighting" },
  { value: "15820", label: "Limited liability companies" },
  { value: "15721", label: "Liquor and cannabis board" },
  { value: "15799", label: "Litter and littering" },
  { value: "15652", label: "Livestock" },
  { value: "15855", label: "Loans" },
  { value: "15783", label: "Lobbying and lobbyists" },
  { value: "15456", label: "Local government" },
  { value: "15754", label: "Lodging" },
  { value: "15537", label: "Long-term care" },
  { value: "15910", label: "Lottery, state" },
  { value: "15437", label: "Low-income persons" },
  { value: "15934", label: "Lunar new year" },
  { value: "16132", label: "Main street program" },
  { value: "15588", label: "Manicurists" },
  { value: "15810", label: "Manufactured and mobile homes" },
  { value: "15691", label: "Manufacturing and technology" },
  { value: "15987", label: "Maps and mapping" },
  { value: "15710", label: "Marijuana" },
  { value: "15762", label: "Marine waters, state" },
  { value: "15469", label: "Marriage and married persons" },
  { value: "15632", label: "Medal of valor" },
  { value: "15941", label: "Medicaid" },
  { value: "15740", label: "Medical assistants" },
  { value: "15666", label: "Medical commission" },
  { value: "15976", label: "Medications" },
  { value: "15578", label: "Meetings, public" },
  { value: "15862", label: "Men and boys" },
  { value: "15504", label: "Mental health" },
  { value: "15739", label: "Mental health counselors" },
  { value: "15914", label: "Metals" },
  { value: "15467", label: "Military" },
  { value: "15541", label: "Military department" },
  { value: "15485", label: "Minorities" },
  { value: "15601", label: "Minors" },
  { value: "16092", label: "Missing persons" },
  { value: "15983", label: "Moorage facilities" },
  { value: "15562", label: "Motor vehicles" },
  { value: "15720", label: "Motorcycles" },
  { value: "16130", label: "Municipal corporations" },
  { value: "16032", label: "Municipal research and services center" },
  { value: "15701", label: "Municipalities" },
  { value: "16002", label: "Museums" },
  { value: "15827", label: "Music and musicians" },
  { value: "15606", label: "Name changes" },
  { value: "15445", label: "Named acts" },
  { value: "16083", label: "National guard" },
  { value: "15978", label: "Natural disasters" },
  { value: "15807", label: "Natural gas" },
  { value: "15638", label: "Natural resources, department" },
  { value: "15811", label: "News media" },
  { value: "15879", label: "Newspapers" },
  { value: "15781", label: "Nonprofit corporations" },
  { value: "15571", label: "Nonprofit organizations" },
  { value: "16090", label: "Northwest power and conservation council" },
  { value: "16146", label: "Notaries public" },
  { value: "15917", label: "Nurses and nursing" },
  {
    value: "15859",
    label: "Nursing care quality assurance commission",
  },
  { value: "16067", label: "Nursing, board" },
  { value: "15484", label: "Observances and holidays" },
  {
    value: "15659",
    label: "Occupational therapy and occupational therapists",
  },
  { value: "16133", label: "Ocean waters and resources" },
  { value: "15598", label: "Official state designations" },
  { value: "15616", label: "Oil and gas" },
  { value: "15577", label: "Open public meetings" },
  { value: "16129", label: "Operating agencies" },
  { value: "15511", label: "Opioids" },
  { value: "15883", label: "Oregon" },
  { value: "15674", label: "Osteopathic medicine and surgery" },
  { value: "16029", label: "Outdoor recreation" },
  { value: "16106", label: "Overburdened communities" },
  { value: "15863", label: "Paraeducator board" },
  { value: "15584", label: "Paraeducators" },
  { value: "16004", label: "Parentage" },
  { value: "15898", label: "Parking" },
  { value: "15748", label: "Parks  " },
  { value: "15452", label: "Parks and recreation commission" },
  { value: "16050", label: "Pawnbrokers" },
  { value: "15891", label: "Pedestrians" },
  {
    value: "15680",
    label: "Performing arts and performance facilities",
  },
  { value: "15681", label: "Personal property" },
  { value: "15593", label: "Pest control and pesticides" },
  { value: "15918", label: "Pets" },
  { value: "15825", label: "Pharmacies and pharmacists" },
  { value: "15826", label: "Pharmacy benefit managers" },
  { value: "16049", label: "Pharmacy quality assurance commission" },
  { value: "15660", label: "Physical therapy and physical therapists" },
  { value: "16055", label: "Physician assistants" },
  { value: "15673", label: "Physicians and surgeons" },
  { value: "16009", label: "Plumbers and plumbing" },
  { value: "15474", label: "Police" },
  { value: "15834", label: "Political subdivisions" },
  { value: "15901", label: "Pollution" },
  { value: "15690", label: "Pollution control hearings board" },
  { value: "15838", label: "Pollution liability insurance agency" },
  { value: "15463", label: "Port districts" },
  { value: "15977", label: "Prescription drugs" },
  { value: "16044", label: "Private investigators" },
  { value: "15561", label: "Productivity board" },
  {
    value: "15525",
    label: "Professional educator standards board (pesb)",
  },
  { value: "15523", label: "Professions" },
  { value: "15573", label: "Property tax" },
  { value: "15623", label: "Prosecuting attorneys" },
  { value: "15715", label: "Protection orders" },
  { value: "16059", label: "Protection product guarantees" },
  { value: "15670", label: "Psychologists" },
  { value: "15540", label: "Public assistance" },
  { value: "15661", label: "Public defense, office" },
  { value: "15819", label: "Public disclosure" },
  { value: "15777", label: "Public disclosure commission" },
  { value: "15519", label: "Public employees&#x27; benefits board" },
  {
    value: "15520",
    label: "Public employees&#x27; retirement system (pers)",
  },
  { value: "15532", label: "Public employment and employees" },
  { value: "16147", label: "Public employment relations commission" },
  { value: "15486", label: "Public facilities districts" },
  { value: "15563", label: "Public funds and accounts" },
  { value: "16057", label: "Public guardianship, office of" },
  { value: "15459", label: "Public lands" },
  { value: "15900", label: "Public policy, institute for" },
  { value: "15723", label: "Public records" },
  {
    value: "16030",
    label: "Public records exemptions accountability committee",
  },
  {
    value: "15711",
    label: "Public safety employees&#x27; retirement system (psers)",
  },
  { value: "16042", label: "Public safety telecommunicators" },
  { value: "15871", label: "Public transit" },
  { value: "16119", label: "Public transportation benefit areas" },
  { value: "15644", label: "Public utilities" },
  { value: "15885", label: "Public utility districts" },
  { value: "15554", label: "Public utility tax" },
  { value: "15700", label: "Public works" },
  { value: "15763", label: "Puget sound" },
  { value: "16091", label: "Puget sound partnership" },
  { value: "15462", label: "Railroads" },
  { value: "15501", label: "Real estate and real property" },
  { value: "15802", label: "Real estate brokers" },
  { value: "15722", label: "Records" },
  { value: "16028", label: "Recreation" },
  { value: "15975", label: "Recreation and conservation office" },
  { value: "16079", label: "Recreational vehicles" },
  { value: "15775", label: "Recycling" },
  { value: "16125", label: "Redistricting" },
  { value: "16124", label: "Redistricting commission" },
  { value: "15908", label: "Regional transit authorities" },
  { value: "16064", label: "Register, washington state (wsr)" },
  {
    value: "16023",
    label: "Regulatory innovation and assistance, office",
  },
  { value: "15656", label: "Religion and religious organizations" },
  { value: "15979", label: "Restaurants" },
  { value: "15471", label: "Retirement and pensions" },
  { value: "15952", label: "Retirement systems, department" },
  { value: "15794", label: "Revenue, department" },
  { value: "15734", label: "Revised code of washington" },
  { value: "15453", label: "Rivers and streams" },
  { value: "15454", label: "Roads and highways" },
  { value: "16070", label: "Rocks and minerals" },
  { value: "15928", label: "Rural areas and rural development" },
  { value: "15972", label: "Salaries" },
  { value: "15699", label: "Sales" },
  { value: "15551", label: "Sales tax" },
  {
    value: "15579",
    label: "School directors&#x27; association, washington state",
  },
  {
    value: "15522",
    label: "School employees&#x27; retirement system (sers)",
  },
  { value: "15447", label: "Schools and school districts" },
  { value: "16027", label: "Science" },
  { value: "16114", label: "Scrap processors and hulk haulers" },
  { value: "16126", label: "Search and rescue" },
  { value: "15771", label: "Secretary of state" },
  { value: "15906", label: "Securities" },
  { value: "16045", label: "Security guards" },
  { value: "15482", label: "Senate resolutions" },
  { value: "15854", label: "Senior citizens" },
  { value: "15446", label: "Sentences and sentencing" },
  { value: "15758", label: "Sentencing guidelines commission" },
  { value: "16060", label: "Service contracts" },
  { value: "15902", label: "Sewage and sewers" },
  { value: "16118", label: "Sex offender policy board" },
  { value: "15613", label: "Sex offenses and offenders" },
  { value: "15861", label: "Sexual orientation" },
  { value: "15816", label: "Sexually violent predators" },
  { value: "15534", label: "Shellfish" },
  {
    value: "15911",
    label: "Sheriffs and police chiefs, washington association of (waspc)",
  },
  { value: "15764", label: "Shorelines and shoreline management" },
  { value: "16099", label: "Shorelines hearings board" },
  { value: "15538", label: "Social and health services, department" },
  { value: "15608", label: "Social workers" },
  { value: "15935", label: "Solar energy and solar projects" },
  { value: "15646", label: "Solid waste" },
  { value: "15465", label: "Special and special purpose districts" },
  { value: "15612", label: "Special education" },
  { value: "16110", label: "Special license plates" },
  { value: "15487", label: "Sports and recreation" },
  { value: "15678", label: "Stadiums and other venues" },
  { value: "15945", label: "Stalking" },
  { value: "15440", label: "State agencies and departments" },
  { value: "15973", label: "State capitol committee" },
  { value: "15597", label: "State designations, official" },
  { value: "15867", label: "State environmental policy act (sepa)" },
  { value: "15812", label: "State finance committee" },
  { value: "15478", label: "State government" },
  { value: "15628", label: "State patrol" },
  { value: "15981", label: "Storage facilities" },
  { value: "16136", label: "Streets" },
  { value: "15448", label: "Student achievement council (sac)" },
  { value: "15449", label: "Student financial assistance, office of" },
  { value: "15514", label: "Studies" },
  { value: "15852", label: "Subdivisions" },
  { value: "15568", label: "Substance abuse" },
  { value: "15505", label: "Substance use disorder" },
  {
    value: "15450",
    label: "Superintendent of public instruction, office (ospi)",
  },
  { value: "15990", label: "Superior courts" },
  { value: "15836", label: "Supreme court" },
  { value: "16154", label: "Sustainable food management, center for" },
  { value: "15875", label: "Tax appeals, board" },
  {
    value: "15438",
    label: "Tax preferences - exemptions, credits, deductions, deferrals, etc.",
  },
  { value: "16150", label: "Taxes - aircraft fuel" },
  { value: "15549", label: "Taxes - business and occupation" },
  { value: "16120", label: "Taxes - capital gains" },
  { value: "15756", label: "Taxes - estate" },
  { value: "15555", label: "Taxes - excise" },
  { value: "15857", label: "Taxes - hazardous substances" },
  { value: "15890", label: "Taxes - leasehold excise" },
  { value: "16112", label: "Taxes - litter" },
  { value: "16102", label: "Taxes - motor vehicle fuel" },
  { value: "15572", label: "Taxes - property" },
  { value: "15550", label: "Taxes - public utility tax" },
  { value: "15705", label: "Taxes - real estate sales excise" },
  { value: "15547", label: "Taxes - sales" },
  { value: "16127", label: "Taxes - telephone access line use" },
  { value: "15848", label: "Taxes - tobacco products" },
  { value: "15548", label: "Taxes - use" },
  { value: "15724", label: "Taxes, generally" },
  { value: "15643", label: "Teachers" },
  { value: "15521", label: "Teachers&#x27; retirement system (trs)" },
  { value: "15926", label: "Technology services board" },
  { value: "15702", label: "Telecommunications" },
  { value: "15642", label: "Telemedicine" },
  { value: "16026", label: "Telephones and telephone companies" },
  { value: "15822", label: "Television and televisions" },
  { value: "15960", label: "Theaters" },
  { value: "15830", label: "Therapeutic courts" },
  { value: "15959", label: "Ticket sales and sellers" },
  { value: "16006", label: "Timber" },
  { value: "16038", label: "Time" },
  { value: "15845", label: "Tobacco and tobacco products" },
  { value: "15849", label: "Tobacco products tax" },
  { value: "15860", label: "Tourism" },
  { value: "15576", label: "Towing and tow trucks" },
  { value: "16000", label: "Trade" },
  { value: "15492", label: "Traffic" },
  { value: "15719", label: "Traffic infractions" },
  { value: "15489", label: "Traffic offenses" },
  { value: "15939", label: "Traffic safety commission" },
  { value: "16137", label: "Traffic safety education" },
  { value: "16076", label: "Transgender people" },
  { value: "15461", label: "Transportation" },
  { value: "15921", label: "Transportation commission" },
  { value: "16014", label: "Transportation network companies" },
  { value: "15460", label: "Transportation, department" },
  { value: "15728", label: "Treasurer, state" },
  { value: "15543", label: "Tribes and tribal members" },
  { value: "15881", label: "Trucks" },
  { value: "15980", label: "Unclaimed property" },
  { value: "15574", label: "Unemployment compensation" },
  { value: "15731", label: "Uniform commercial code (ucc)" },
  { value: "15502", label: "Uniform laws" },
  { value: "15817", label: "University of washington" },
  { value: "15552", label: "Use tax" },
  { value: "15637", label: "Utilities" },
  { value: "15639", label: "Utilities and transportation commission" },
  { value: "15631", label: "Vaccination and vaccines" },
  { value: "15846", label: "Vapor products" },
  { value: "16115", label: "Vehicle wreckers" },
  { value: "15803", label: "Vessels" },
  { value: "15468", label: "Veterans" },
  { value: "15524", label: "Veterans affairs, department" },
  { value: "16056", label: "Veterinarians" },
  { value: "15619", label: "Victims of crimes" },
  { value: "15896", label: "Vocational education" },
  {
    value: "15893",
    label:
      "Volunteer firefighters&#x27; and reserve officers&#x27; relief and pension system",
  },
  { value: "15828", label: "Volunteers and volunteering" },
  { value: "15663", label: "Voting and ballots" },
  { value: "15765", label: "Vulnerable adults" },
  { value: "15735", label: "Wages" },
  { value: "15618", label: "Wages and hours" },
  { value: "15971", label: "Wages and salaries" },
  { value: "15873", label: "Warehouse distribution centers" },
  { value: "16063", label: "Washington administrative code (wac)" },
  {
    value: "15963",
    label: "Washington auto theft prevention authority",
  },
  { value: "15995", label: "Washington health corps" },
  { value: "15957", label: "Washington state historical society" },
  { value: "15629", label: "Washington state patrol" },
  { value: "15682", label: "Washington state university" },
  { value: "16155", label: "Waste reduction, office of" },
  { value: "15747", label: "Water" },
  { value: "15792", label: "Water pollution" },
  { value: "15869", label: "Water rights" },
  { value: "15903", label: "Waters of the state" },
  { value: "15887", label: "Water-sewer districts" },
  { value: "15507", label: "Weapons" },
  { value: "15843", label: "Western washington university" },
  { value: "15640", label: "Wildfires" },
  { value: "15651", label: "Wildlife" },
  { value: "15508", label: "Wine and wineries" },
  { value: "15969", label: "Wolves" },
  { value: "15622", label: "Women" },
  { value: "16109", label: "Women&#x27;s commission" },
  { value: "15738", label: "Worker training and workforce needs" },
  { value: "15730", label: "Workers&#x27; compensation" },
  {
    value: "15797",
    label: "Workforce training and education coordinating board",
  },
  { value: "16116", label: "Wreckers, vehicle" },
];
